apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler 
metadata:
  name: hpa
  spec:
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
