apiVersion: apps/v1
kind: Deployment  
metadata:
  name: backend-app
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  strategy: 
    type: RollingUpdate 
  template: 
    metadata: 
      labels:
        app: backend-app 
    spec:
      containers:
      - name: backend-app 
        image: ritudocer/studentapp
        ports:
        - name: java
          containerPort: 8080
          protocol: TCP 